

# This file was *autogenerated* from the file tp11-jazeron.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_3 = Integer(3); _sage_const_13 = Integer(13); _sage_const_5 = Integer(5); _sage_const_6 = Integer(6); _sage_const_9 = Integer(9); _sage_const_1 = Integer(1); _sage_const_11 = Integer(11); _sage_const_7 = Integer(7); _sage_const_4 = Integer(4); _sage_const_12 = Integer(12); _sage_const_0 = Integer(0); _sage_const_23 = Integer(23); _sage_const_14 = Integer(14); _sage_const_18 = Integer(18); _sage_const_15 = Integer(15); _sage_const_22 = Integer(22); _sage_const_17 = Integer(17); _sage_const_21 = Integer(21); _sage_const_8 = Integer(8); _sage_const_10 = Integer(10); _sage_const_49 = Integer(49)
print("""\
# *************************************************************************** #
# *************************************************************************** #
# TP11 : CODES CORRECTEURS D'ERREURS ALGEBRIQUES                              #
# *************************************************************************** #
# *************************************************************************** #
""")

# CONSIGNES
#
# Les seules lignes a modifier sont annoncee par "Code pour l'exercice"
# indique en commmentaire et son signalees
# Ne changez pas le nom des variables
#
# CONSEILS
#
# Ce modele vous sert a restituer votre travail. Il est deconseille d'ecrire
# une longue suite d'instruction et de debugger ensuite. Il vaut mieux tester
# le code que vous produisez ligne apres ligne, afficher les resultats et
# controler que les objets que vous definissez sont bien ceux que vous attendez.
#
# Vous devez verifier votre code en le testant, y compris par des exemples que
# vous aurez fabrique vous-meme.
#


reset()
print("""\
# ****************************************************************************
# CODE DE HAMMING
# ****************************************************************************
""")


# Donnees de l'enonce de l'exercice

C = codes.HammingCode(GF(_sage_const_2 ),_sage_const_3 )

# Code pour l'EXERCICE

B = C.generator_matrix() # a completer
d = C.minimum_distance() # a completer

# # Affichage des resultats

print( "Le code",C,"a pour matrice")
print( B)
print( "et pour distance minimale d=",d)


reset()
print("""\
# ****************************************************************************
# DECODAGE DE BERLEKAMP-MASSEY
# ****************************************************************************
""")


# Donnees de l'enonce de l'exercice

from sage.matrix.berlekamp_massey import berlekamp_massey

q=_sage_const_13 
Fq = FiniteField(q)
k=_sage_const_5 
alpha=Fq(_sage_const_6 )
PolFq = PolynomialRing(Fq, names=('x',)); (x,) = PolFq._first_ngens(1)
r = vector(Fq,[_sage_const_5 ,_sage_const_2 ,_sage_const_9 ,_sage_const_9 ,_sage_const_1 ,_sage_const_11 ,_sage_const_7 ,_sage_const_5 ,_sage_const_7 ,_sage_const_4 ,_sage_const_3 ,_sage_const_1 ])

# Code pour l'EXERCICE

G = matrix([[z**j for z in [alpha**i for i in range(_sage_const_12 )]] for j in range(k)])
H = matrix([[z**j for z in [alpha**i for i in range(_sage_const_12 )]] for j in range(_sage_const_1 ,_sage_const_12 -k+_sage_const_1 )])
s = H*r
sigma = PolFq(berlekamp_massey(list(s)[:-_sage_const_1 ]).reverse())
M = []
for i in range(_sage_const_12 ):
    if sigma(alpha**(-i))==Fq(_sage_const_0 ):
        M.append(i)

r = list(r)
r = [r[j] for j in range(len(r)) if j not in M]
r = vector(r)

G = G.matrix_from_columns([i for i in range(_sage_const_12 ) if i not in M ])
m = G.solve_left(r)

# # Affichage des resultats

print( "La matrice génératrice du code est")
print( G)
print( "La matrice de controle du code est")
print( H)
print( "Le syndrome est")
print( s)
print( "Le polynome localisateur d'erreurs est")
print( sigma)
print( "La position des erreurs est")
print( M)
print( "Le message envoye le plus probable est")
print( m)



reset()
print("""\
# ****************************************************************************
# DECODAGE EN LISTE
# ****************************************************************************
""")


# Donnees de l'enonce de l'exercice

q=_sage_const_23 
Fq = FiniteField(q)
k = _sage_const_3 
alpha=Fq(_sage_const_14 )
MPol = PolynomialRing(Fq,_sage_const_2 , names=('x', 'y',)); (x, y,) = MPol._first_ngens(2)
 
r=vector(Fq, [_sage_const_12 ,_sage_const_18 ,_sage_const_15 ,_sage_const_22 ,_sage_const_17 ,_sage_const_5 ,_sage_const_14 ,_sage_const_21 ,_sage_const_17 ,_sage_const_4 ,_sage_const_13 ,_sage_const_8 ,_sage_const_4 ,_sage_const_10 , _sage_const_15 ,_sage_const_11 ,_sage_const_22 ,_sage_const_12 ,_sage_const_13 ,_sage_const_9 ,_sage_const_14 ,_sage_const_12 ])

# Code pour l'EXERCICE

b1= floor((_sage_const_22 -_sage_const_3 +_sage_const_1 )/_sage_const_2 )
b2= _sage_const_22  - ceil(sqrt(_sage_const_2 *(k-_sage_const_1 )*_sage_const_22 )) 

liste_exposants = []
i,j = _sage_const_0 , _sage_const_0 
liste_exposants.append((i,j))
while i+_sage_const_2 *j < _sage_const_22  - sqrt(_sage_const_2 *(k-_sage_const_1 )*_sage_const_22 ) :
    j+= _sage_const_1 
    while i+_sage_const_2 *j < _sage_const_22  - sqrt(_sage_const_2 *(k-_sage_const_1 )*_sage_const_22 ) :
        liste_exposants.append((i,j))
        i+=_sage_const_1 
    i=_sage_const_0 
            
M = matrix(Fq, [[((alpha**k)**i)*(r[k])**j for k in range(_sage_const_22 )] for (i,j) in liste_exposants])

F = kernel(M)
base = F.basis()

polynomes = []

for p in base :
    polynomes.append(sum([p[i]*x**liste_exposants[i][_sage_const_0 ]*y**liste_exposants[i][_sage_const_1 ] for i in range(len(p))]))

facteurs = []    

for p in polynomes :
    for q,_ in p.factor():
        if q.polynomial(y).degree() == _sage_const_1  : # on récupère les facteurs de degré 1 en y
            facteurs.append((-q+y).polynomial(x)) 

facteurs = set(facteurs)

facteurs_finaux = []

for f in facteurs : # on regarde les polynomes qui vérifient ce que l'on veut 
    if f.degree() < k and len([i for i in range(len(r)) if f(alpha**i) == r[i]]) >= _sage_const_22 -_sage_const_12  :
        facteurs_finaux.append(f)
    

G = matrix([[z**j for z in [alpha**i for i in range(_sage_const_22 )]] for j in range(k)])   

L = [vector(Fq,[f(alpha**i) for i in range(_sage_const_22 )]) for f in facteurs_finaux] # on récupère les mots de codes de la liste
MM = [G.solve_left(c) for c in L]
M = []
for m in MM :
    M.append([chr(Integer(x)+ord('a')) for x in m])
    
d1 = len([i for i in range(len(r)) if r[i]!=L[_sage_const_0 ][i]]) # compter la distance entre r et le premier mot de code
d2 = len([i for i in range(len(r)) if r[i]!=L[_sage_const_1 ][i]]) # idem avec le deuxième mot de code

if d1 > d2 : # on choisit le mot de code le plus proche de R
    c = L[_sage_const_1 ]
    m = M[_sage_const_1 ]
else : 
    c = L[_sage_const_0 ]
    m = M[_sage_const_0 ]
    


# # Affichage des resultats

print( "Le decodage unique fonctionne jusqu'à distance",b1)
print( "Le decodage de Sudan fonctionne jusqu'à distance",b2)
print( "La liste des mots de code les plus proches de r est",L)
print( "Elle correspond aux messages")
print( M)
print( "Le mot de code le plus probable est",c)
print( "soit le message",m)


reset()
print("""\
# ****************************************************************************
# CODE ALGEBRIQUE
# ****************************************************************************
""")


# ESSAYEZ DE LE TRAITER
# CET EXERCICE NE SERA PAS EVALUE
# IL VOUS MANQUE LE THEOREME DE RIEMANN-ROCH POUR TOUT COMPRENDRE


reset()
print("""\
# ****************************************************************************
# BORNES
# ****************************************************************************
""")


# Donnees de l'enonce de l'exercice

q=_sage_const_49 

# Code pour l'EXERCICE

def hq(x,q) :
    if x == _sage_const_0  :
        return _sage_const_0 
    elif x <= _sage_const_1  - _sage_const_1 /q : 
        return x*log(q-_sage_const_1 ,q) - x*log(x,q) - (_sage_const_1 -x)*log(_sage_const_1 -x,q)

gv = lambda x : _sage_const_1  - hq(x,q)
plotkin = lambda x : _sage_const_1 - x/(_sage_const_1 -_sage_const_1 /q)
hamming = lambda x : _sage_const_1  - hq(x/_sage_const_2 ,q)
mrrw = lambda x : hq(_sage_const_1 /q*(q-_sage_const_1 -(q-_sage_const_2 )*x-_sage_const_2 *sqrt((q-_sage_const_1 )*x*(_sage_const_1 -x))),q)

# # Affichage des resultats

plot([gv,plotkin,hamming,mrrw],xmin=_sage_const_0 ,xmax=_sage_const_1 ,ymin=_sage_const_0 ,ymax=_sage_const_1 , legend_label=["GV","Plotkin","Hamming","MRRW"],title="Differentes bornes sur les codes")
print("""\
# ****************************************************************************
# BORNES BATTANT GILBERT-VARSHAMOV
# ****************************************************************************
""")


# Donnees de l'enonce de l'exercice

# Code pour l'EXERCICE

codesalg = lambda x : _sage_const_1  - _sage_const_1 /(sqrt(q)-_sage_const_1 ) - x

# # Affichage des resultats

plot([gv,plotkin,hamming,mrrw,codesalg],xmin=_sage_const_0 ,xmax=_sage_const_1 ,ymin=_sage_const_0 ,ymax=_sage_const_1 , legend_label=["GV","Plotkin","Hamming","MRRW","Codes Algebriques"],title="Differentes bornes sur les codes")

